name: myflutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_webview_plugin: ^0.3.2
  http: ^0.12.0+1
  flutter_screenutil: ^0.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/a.jpg
   - images/2.0x/a.jpg
   - images/3.0x/a.jpg
   - images/4.0x/a.jpg

   - images/aijqr.png
   - images/bkyqy.png
   - images/cgxt.png
   - images/cybkt.png
   - images/czd.png
   - images/gdyw.png
   - images/gg.png
   - images/gszb.png
   - images/hot.png
   - images/hq.png
   - images/jcgj.png
   - images/jp.png
   - images/jy.png
   - images/kxds.png
   - images/mncg.png
   - images/new.png
   - images/pysq.png
   - images/qqjy.png
   - images/sjzx.png
   - images/spgs.png
   - images/sqmdh.png
   - images/wdjf.png
   - images/wgjc.png
   - images/xgmm.png
   - images/xgsg.png
   - images/yhk.png
   - images/yzzz.png
   - images/zhjc.png
   - images/znxg.png
   - images/zxg.png

   
   - images/2.0x/aijqr.png
   - images/2.0x/bkyqy.png
   - images/2.0x/cgxt.png
   - images/2.0x/cybkt.png
   - images/2.0x/czd.png
   - images/2.0x/gdyw.png
   - images/2.0x/gg.png
   - images/2.0x/gszb.png
   - images/2.0x/hot.png
   - images/2.0x/hq.png
   - images/2.0x/jcgj.png
   - images/2.0x/jp.png
   - images/2.0x/jy.png
   - images/2.0x/kxds.png
   - images/2.0x/mncg.png
   - images/2.0x/new.png
   - images/2.0x/pysq.png
   - images/2.0x/qqjy.png
   - images/2.0x/sjzx.png
   - images/2.0x/spgs.png
   - images/2.0x/sqmdh.png
   - images/2.0x/wdjf.png
   - images/2.0x/wgjc.png
   - images/2.0x/xgmm.png
   - images/2.0x/xgsg.png
   - images/2.0x/yhk.png
   - images/2.0x/yqhy.png
   - images/2.0x/yzzz.png
   - images/2.0x/zhjc.png
   - images/2.0x/znxg.png
   - images/2.0x/zxg.png

   - images/3.0x/aijqr.png
   - images/3.0x/bkyqy.png
   - images/3.0x/cgxt.png
   - images/3.0x/cybkt.png
   - images/3.0x/czd.png
   - images/3.0x/gdyw.png
   - images/3.0x/gg.png
   - images/3.0x/gszb.png
   - images/3.0x/hot.png
   - images/3.0x/hq.png
   - images/3.0x/jcgj.png
   - images/3.0x/jp.png
   - images/3.0x/jy.png
   - images/3.0x/kxds.png
   - images/3.0x/mncg.png
   - images/3.0x/new.png
   - images/3.0x/pysq.png
   - images/3.0x/qqjy.png
   - images/3.0x/sjzx.png
   - images/3.0x/spgs.png
   - images/3.0x/sqmdh.png
   - images/3.0x/wdjf.png
   - images/3.0x/wgjc.png
   - images/3.0x/xgmm.png
   - images/3.0x/xgsg.png
   - images/3.0x/yhk.png
   - images/3.0x/yqhy.png
   - images/3.0x/yzzz.png
   - images/3.0x/zhjc.png
   - images/3.0x/znxg.png
   - images/3.0x/zxg.png


   - images/4.0x/aijqr.png
   - images/4.0x/bkyqy.png
   - images/4.0x/cgxt.png
   - images/4.0x/cybkt.png
   - images/4.0x/czd.png
   - images/4.0x/gdyw.png
   - images/4.0x/gg.png
   - images/4.0x/gszb.png
   - images/4.0x/hot.png
   - images/4.0x/hq.png
   - images/4.0x/jcgj.png
   - images/4.0x/jp.png
   - images/4.0x/jy.png
   - images/4.0x/kxds.png
   - images/4.0x/mncg.png
   - images/4.0x/new.png
   - images/4.0x/pysq.png
   - images/4.0x/qqjy.png
   - images/4.0x/sjzx.png
   - images/4.0x/spgs.png
   - images/4.0x/sqmdh.png
   - images/4.0x/wdjf.png
   - images/4.0x/wgjc.png
   - images/4.0x/xgmm.png
   - images/4.0x/xgsg.png
   - images/4.0x/yhk.png
   - images/4.0x/yqhy.png
   - images/4.0x/yzzz.png
   - images/4.0x/zhjc.png
   - images/4.0x/znxg.png
   - images/4.0x/zxg.png

  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
